name: expensy
description: A privacy-first expense manager with no internet permission.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  intl: ^0.20.2
  fl_chart: ^0.68.0
  google_ml_kit: ^0.16.0
  image_picker: ^1.0.7
  receipt_recognition: ^0.2.8
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  uuid: ^4.3.3
  path: ^1.9.0
  share_plus: ^7.2.2
  csv: ^6.0.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
