name: expensy
description: A fully offline, feature-rich expense manager with Material You design.
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
   sqflite: ^2.4.2+1
  path_provider: ^2.1.5
  intl: ^0.20.2
  fl_chart: ^1.20.0
  google_ml_kit: ^0.21.0
  image_picker: ^1.2.2
  receipt_recognition: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  meta: ^1.18.2
  vector_math: ^2.3.0
  xml: ^7.0.1
  lints: ^6.1.0
  matcher: ^0.12.20
  test_api: ^0.7.12
  file_picker: 8.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/splash_icon.png

